# Generated by Django 4.0.8 on 2023-01-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(help_text='Обязательно для заполнения.Максимум 150 букв.', max_length=150, verbose_name='Пароль'),
        ),
    ]
