# Generated by Django 4.0.8 on 2023-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
