# Generated by Django 4.0.8 on 2023-02-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='banned',
        ),
        migrations.AddField(
            model_name='myuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name=' Активирован'),
        ),
    ]
